### Recuperar info. del pokemon ditto
GET http://localhost:1234/pokemon/ditto

### Creación de un Pokemon
POST http://localhost:1234/pokemon
Content-Type : application/json

{
  "name": "ditto",
  "type": "normal",
  "moves":[
    "transform"
  ]
}